source 'https://rubygems.org'
ruby "1.9.3"

gem 'rails',                '3.2.12'
gem 'jquery-rails'
gem 'pg'
gem 'devise'
gem 'thin'

group :assets do
  gem 'sass-rails'
  gem 'uglifier'
end

group :development do
  gem 'mailcatcher'
end

group :test do
  gem 'minitest'
  gem 'capybara'
end

group :development, :test do
  gem 'pry-rails'
end
